apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: self-healing-bot-pdb
  namespace: self-healing-bot
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: self-healing-bot
      component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: celery-worker-pdb
  namespace: self-healing-bot
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: self-healing-bot
      component: worker