apiVersion: v1
kind: Secret
metadata:
  name: self-healing-bot-secrets
  namespace: self-healing-bot
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  GITHUB_APP_ID: bXlfdGVzdF9hcHBfaWQ=  # my_test_app_id
  GITHUB_WEBHOOK_SECRET: bXlfc3VwZXJfc2VjcmV0X3dlYmhvb2s=  # my_super_secret_webhook
  DATABASE_PASSWORD: bXlfc3VwZXJfc2VjcmV0X3Bhc3N3b3Jk  # my_super_secret_password 
  SECRET_KEY: bXlfc3VwZXJfc2VjcmV0X2tleV9mb3JfZGV2ZWxvcG1lbnQ=  # my_super_secret_key_for_development
  ENCRYPTION_KEY: bXlfc3VwZXJfc2VjcmV0X2VuY3J5cHRpb25fa2V5XzMyX2J5dGVzX2xvbmc=  # my_super_secret_encryption_key_32_bytes_long
---
apiVersion: v1
kind: Secret
metadata:
  name: github-private-key
  namespace: self-healing-bot
type: Opaque
data:
  # Base64 encoded GitHub App private key - replace with actual key
  private-key.pem: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpQUklWQVRFX0tFWV9DT05URU5UX0hFUkUK
    LS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K