apiVersion: v1
kind: Namespace
metadata:
  name: mlops-bot-prod
  labels:
    app: self-healing-mlops-bot
    environment: production
    tier: core
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mlops-bot-resource-quota
  namespace: mlops-bot-prod
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mlops-bot-limit-range
  namespace: mlops-bot-prod
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "128Mi"
    type: Container
  - max:
      storage: "100Gi"
    type: PersistentVolumeClaim