apiVersion: v1
kind: Namespace
metadata:
  name: self-healing-mlops-staging
  labels:
    app: self-healing-mlops-bot
    environment: staging
    version: v1.0.0
    compliance: global
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: self-healing-mlops
---